version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: chroniccare/ecp-sds-hardfork-cc:latest
    container_name:  ecp-sds-hardfork-cc
    restart: on-failure
    ports:
      - "8080:8080"
  web:
    image: chroniccare/introspect 
    ports:
      - "8181:8181"
